In [75]:
import numpy as np
import pandas as pd
z=pd.read_csv(r"C:\Users\ruthu\Downloads\raw_students.csv")
z

   StudentID          Name     Age  Gender  Score                Email
0          1      John doe      20    male   85.0     john@example.com
1          2   Jane Smith       19  Female   90.0  janesmith@email.com
2          3   Bob Johnson     NaN    Male   78.0       bobj@email.com
3          4   Alice Brown      21  Female    NaN      alice@email.com
4          5     Chris Lee  twenty    Male   88.0          chris@email
5          6      John Doe      20    Male   85.0     john@example.com
6          7           NaN      22  Female   92.0      sarah@email.com
7          8  Michael King      23    Male   75.0    michael@email.com

In [76]:
z.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  8 non-null      int64
 1   Name       7 non-null      object
 2   Age        7 non-null      object
 3   Gender     8 non-null      object
 4   Score      7 non-null      float64
 5   Email      8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [77]:
z["Age"]=pd.to_numeric(z["Age"],errors="coerce")

In [78]:
z.dtypes

StudentID      int64
Name          object
Age          float64
Gender        object
Score        float64
Email         object
dtype: object

In [79]:
z

   StudentID          Name   Age  Gender  Score                Email
0          1      John doe  20.0    male   85.0     john@example.com
1          2   Jane Smith   19.0  Female   90.0  janesmith@email.com
2          3   Bob Johnson   NaN    Male   78.0       bobj@email.com
3          4   Alice Brown  21.0  Female    NaN      alice@email.com
4          5     Chris Lee   NaN    Male   88.0          chris@email
5          6      John Doe  20.0    Male   85.0     john@example.com
6          7           NaN  22.0  Female   92.0      sarah@email.com
7          8  Michael King  23.0    Male   75.0    michael@email.com

In [80]:
z.isnull().sum()

StudentID    0
Name         1
Age          2
Gender       0
Score        1
Email        0
dtype: int64

In [82]:
z

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male   85.0     john@example.com
1          2   Jane Smith   19.000000  Female   90.0  janesmith@email.com
2          3   Bob Johnson  20.833333    Male   78.0       bobj@email.com
3          4   Alice Brown  21.000000  Female    NaN      alice@email.com
4          5     Chris Lee  20.833333    Male   88.0          chris@email
5          6      John Doe  20.000000    Male   85.0     john@example.com
6          7           NaN  22.000000  Female   92.0      sarah@email.com
7          8  Michael King  23.000000    Male   75.0    michael@email.com

In [83]:
z["Score"].fillna(value=z["Score"].median(),inplace=True)
z

C:\Users\ruthu\AppData\Local\Temp\ipykernel_24292\1361617597.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  z["Score"].fillna(value=z["Score"].median(),inplace=True)

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male   85.0     john@example.com
1          2   Jane Smith   19.000000  Female   90.0  janesmith@email.com
2          3   Bob Johnson  20.833333    Male   78.0       bobj@email.com
3          4   Alice Brown  21.000000  Female   85.0      alice@email.com
4          5     Chris Lee  20.833333    Male   88.0          chris@email
5          6      John Doe  20.000000    Male   85.0     john@example.com
6          7           NaN  22.000000  Female   92.0      sarah@email.com
7          8  Michael King  23.000000    Male   75.0    michael@email.com

In [84]:
z["Age"]=z["Age"].astype("int")
z

   StudentID          Name  Age  Gender  Score                Email
0          1      John doe   20    male   85.0     john@example.com
1          2   Jane Smith    19  Female   90.0  janesmith@email.com
2          3   Bob Johnson   20    Male   78.0       bobj@email.com
3          4   Alice Brown   21  Female   85.0      alice@email.com
4          5     Chris Lee   20    Male   88.0          chris@email
5          6      John Doe   20    Male   85.0     john@example.com
6          7           NaN   22  Female   92.0      sarah@email.com
7          8  Michael King   23    Male   75.0    michael@email.com

In [85]:
z["Name"]=z["Name"].fillna("Unknowm")
z

   StudentID          Name  Age  Gender  Score                Email
0          1      John doe   20    male   85.0     john@example.com
1          2   Jane Smith    19  Female   90.0  janesmith@email.com
2          3   Bob Johnson   20    Male   78.0       bobj@email.com
3          4   Alice Brown   21  Female   85.0      alice@email.com
4          5     Chris Lee   20    Male   88.0          chris@email
5          6      John Doe   20    Male   85.0     john@example.com
6          7       Unknowm   22  Female   92.0      sarah@email.com
7          8  Michael King   23    Male   75.0    michael@email.com

In [112]:
z.Name.duplicated().sum()

np.int64(1)

In [108]:
z["Name"]=z["Name"].str.title()

In [109]:
z["Name"].str.title()

0        John Doe
1     Jane Smith
2     Bob Johnson
3     Alice Brown
4       Chris Lee
5        John Doe
6         Unknowm
7    Michael King
Name: Name, dtype: object

In [110]:
z["Gender"]=z["Gender"].str.capitalize()
z

   StudentID          Name  Age  Gender  Score                Email
0          1      John Doe   20    Male   85.0     john@example.com
1          2   Jane Smith    19  Female   90.0  janesmith@email.com
2          3   Bob Johnson   20    Male   78.0       bobj@email.com
3          4   Alice Brown   21  Female   85.0      alice@email.com
4          5     Chris Lee   20    Male   88.0          chris@email
5          6      John Doe   20    Male   85.0     john@example.com
6          7       Unknowm   22  Female   92.0      sarah@email.com
7          8  Michael King   23    Male   75.0    michael@email.com

In [118]:
z[z["Email"].str.contains(".com")]

   StudentID          Name  Age  Gender  Score                Email
0          1      John Doe   20    Male   85.0     john@example.com
1          2   Jane Smith    19  Female   90.0  janesmith@email.com
2          3   Bob Johnson   20    Male   78.0       bobj@email.com
3          4   Alice Brown   21  Female   85.0      alice@email.com
5          6      John Doe   20    Male   85.0     john@example.com
6          7       Unknowm   22  Female   92.0      sarah@email.com
7          8  Michael King   23    Male   75.0    michael@email.com