In [1]:
#pandas

In [2]:
import pandas as pd
import numpy as np

In [6]:
data=pd.Series([1,2,3,4])
data

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
data=pd.Series([1,2,3,4],index=["a","b","c","d"])
data

a    1
b    2
c    3
d    4
dtype: int64

In [13]:
data.name="Numbers"
data

a    1
b    2
c    3
d    4
Name: Numbers, dtype: int64

In [10]:
data.size

4

In [11]:
len(data)

4

In [14]:
data.shape

(4,)

In [15]:
data.values

array([1, 2, 3, 4])

In [21]:
data["b"],data["a"],data["c"]

(np.int64(2), np.int64(1), np.int64(3))

In [22]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [30]:
data.loc["a"::2],data.iloc[3]

(a    1
 c    3
 Name: Numbers, dtype: int64,
 np.int64(4))

In [34]:
data.loc["a"::2],data.iloc[1]

(a    1
 c    3
 Name: Numbers, dtype: int64,
 np.int64(2))

In [38]:
data.loc[["a","b","c"]],data.iloc[3]

(a    1
 b    2
 c    3
 Name: Numbers, dtype: int64,
 np.int64(4))

In [39]:
#data frames

In [45]:
dictionary = {
     "usn":[1,2,3,4],
    "name":["ruthu","uujgooooooo","ghghhhhhh","fguyegggggggg"],
    "branch":["CSE","ise","aiml","eee"],
    "age":[22,21,32,44]
}

In [46]:
df = pd.DataFrame(dictionary)
df

   usn           name branch  age
0    1          ruthu    CSE   22
1    2    uujgooooooo    ise   21
2    3      ghghhhhhh   aiml   32
3    4  fguyegggggggg    eee   44

In [53]:
d=pd.read_csv(r"C:\Users\ruthu\Downloads\sample.csv")
d

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,2015-09-30,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,2021-11-05,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,2010-04-18,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2022-02-14,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,2013-12-01,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,2020-08-19,Bangalore,4.0
10,10,111,Ravi,HR,33,47000,6,2017-05-23,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,2019-09-17,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,2008-03-11,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,2021-07-29,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,2014-01-10,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [54]:
d.tail(10)

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
10,10,111,Ravi,HR,33,47000,6,2017-05-23,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,2019-09-17,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,2008-03-11,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,2021-07-29,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,2014-01-10,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [56]:
d.describe()

,Unnamed: 0,EmpID,Age,Salary,Experience,PerformanceScore
count,20.00000,20.00000,20.000000,20.000000,20.000000,20.000000
mean,9.50000,110.50000,32.700000,59875.000000,7.400000,4.190000
std,5.91608,5.91608,5.449288,13388.796377,4.615762,0.415363
min,0.00000,101.00000,25.000000,45000.000000,2.000000,3.500000
25%,4.75000,105.75000,28.750000,50750.000000,4.000000,3.900000
50%,9.50000,110.50000,31.500000,56500.000000,6.000000,4.150000
75%,14.25000,115.25000,36.250000,61250.000000,10.250000,4.425000
max,19.00000,120.00000,45.000000,90000.000000,18.000000,4.900000

In [57]:
d.tail()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [58]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20 non-null     int64
 1   EmpID             20 non-null     int64
 2   Name              20 non-null     object
 3   Department        20 non-null     object
 4   Age               20 non-null     int64
 5   Salary            20 non-null     int64
 6   Experience        20 non-null     int64
 7   JoiningDate       20 non-null     object
 8   City              20 non-null     object
 9   PerformanceScore  20 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 1.7+ KB

In [61]:
d.shape

(20, 10)

In [64]:
d.sample()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
8,8,109,Sara,Finance,38,61000,12,2013-12-01,Delhi,4.3

In [65]:
d.head()
d

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,2015-09-30,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,2021-11-05,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,2010-04-18,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2022-02-14,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,2013-12-01,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,2020-08-19,Bangalore,4.0
10,10,111,Ravi,HR,33,47000,6,2017-05-23,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,2019-09-17,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,2008-03-11,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,2021-07-29,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,2014-01-10,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [66]:
d["Name"]

0       Ram
1     Shyam
2     Geeta
3     Anita
4     Kiran
5      John
6     Meena
7     David
8      Sara
9     Arjun
10     Ravi
11    Priya
12    Kunal
13    Sneha
14    Vijay
15     Neha
16     Amit
17    Pooja
18    Rahul
19    Divya
Name: Name, dtype: object

In [68]:
d.Name

0       Ram
1     Shyam
2     Geeta
3     Anita
4     Kiran
5      John
6     Meena
7     David
8      Sara
9     Arjun
10     Ravi
11    Priya
12    Kunal
13    Sneha
14    Vijay
15     Neha
16     Amit
17    Pooja
18    Rahul
19    Divya
Name: Name, dtype: object

In [71]:
d[["Name","Department","Salary","Experience"]]

     Name Department  Salary  Experience
0     Ram         IT   50000           2
1   Shyam         HR   45000           5
2   Geeta    Finance   60000           4
3   Anita         IT   75000          10
4   Kiran         HR   52000           7
5    John    Finance   58000           3
6   Meena         IT   82000          15
7   David         HR   48000           2
8    Sara    Finance   61000          12
9   Arjun         IT   54000           4
10   Ravi         HR   47000           6
11  Priya    Finance   59000           5
12  Kunal         IT   90000          18
13  Sneha         HR   51000           3
14  Vijay    Finance   62000          11
15   Neha         IT   88000          14
16   Amit         HR   53000           8
17  Pooja    Finance   57000           6
18  Rahul         IT   56000           4
19  Divya         HR   49500           9

In [72]:
d[["Name","Department","Salary","Experience"]].head()

    Name Department  Salary  Experience
0    Ram         IT   50000           2
1  Shyam         HR   45000           5
2  Geeta    Finance   60000           4
3  Anita         IT   75000          10
4  Kiran         HR   52000           7

In [73]:
type(d.Name)

pandas.core.series.Series

In [74]:
du=pd.read_csv(r"C:\Users\ruthu\Downloads\test2.csv")
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [78]:
du.isnull()

   Unnamed: 0   Name    Age  Department  Salary
0       False  False  False       False   False
1       False  False  False       False   False
2       False  False  False       False   False
3       False  False   True       False   False
4       False  False  False       False    True
5       False  False  False       False   False

In [90]:
du.loc[ "1":"3", "Name": "Age"]

      Name   Age
1      Bob  30.0
2  Charlie  35.0
3    David   NaN

In [81]:
du.isnull().

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [91]:
du.loc[ :,:]

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [94]:
du.loc[1:3,"Name":"Department"]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [95]:
du.iloc[1:4, 1:4]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [96]:
du.columns

Index(['Unnamed: 0', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [100]:
du.rename(columns={"Name":"N","Age":"A","Department":"D"},inplace=True)

In [101]:
du

   Unnamed: 0        N     A        D   Salary
0           0    Alice  25.0       HR  50000.0
1           1      Bob  30.0       IT  60000.0
2           2  Charlie  35.0  Finance  70000.0
3           3    David   NaN       IT  62000.0
4           4      Eve  29.0       HR      NaN
5           5    Alice  25.0       HR  50000.0

In [102]:
du=pd.read_csv(r"C:\Users\ruthu\Downloads\test2.csv")
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [107]:
du.rename(columns={"Name":"N","Age":"A","Department":"D"}
          ,inplace=True)
du

         N     A        D   Salary
0    Alice  25.0       HR  50000.0
1      Bob  30.0       IT  60000.0
2  Charlie  35.0  Finance  70000.0
3    David   NaN       IT  62000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  50000.0

In [119]:
du=pd.read_csv(r"C:\Users\ruthu\Downloads\test2.csv")
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [120]:
du.drop('Unnamed: 0',axis=1,inplace=True)
du

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [123]:
du.drop('Name',axis=1,inplace=True)
du

    Age Department   Salary
0  25.0         HR  50000.0
1  30.0         IT  60000.0
2  35.0    Finance  70000.0
3   NaN         IT  62000.0
4  29.0         HR      NaN
5  25.0         HR  50000.0

In [127]:
du["updated_salary"]=du["Salary"]+6000
du

    Age Department   Salary  updated_salary
0  25.0         HR  50000.0         56000.0
1  30.0         IT  60000.0         66000.0
2  35.0    Finance  70000.0         76000.0
3   NaN         IT  62000.0         68000.0
4  29.0         HR      NaN             NaN
5  25.0         HR  50000.0         56000.0

In [129]:
du["updated_salary_2"]=du["Salary"].map(lambda x:x+40900)
du

    Age Department   Salary  updated_salary  updated_salary_2
0  25.0         HR  50000.0         56000.0           90900.0
1  30.0         IT  60000.0         66000.0          100900.0
2  35.0    Finance  70000.0         76000.0          110900.0
3   NaN         IT  62000.0         68000.0          102900.0
4  29.0         HR      NaN             NaN               NaN
5  25.0         HR  50000.0         56000.0           90900.0

In [130]:
du.Age.dtype #cant add int value coz it has null values

dtype('float64')

In [131]:
du.dropna(inplace=True)

In [132]:
du

    Age Department   Salary  updated_salary  updated_salary_2
0  25.0         HR  50000.0         56000.0           90900.0
1  30.0         IT  60000.0         66000.0          100900.0
2  35.0    Finance  70000.0         76000.0          110900.0
5  25.0         HR  50000.0         56000.0           90900.0

In [133]:
du.isnull().sum()

Age                 0
Department          0
Salary              0
updated_salary      0
updated_salary_2    0
dtype: int64

In [134]:
du["Age"]=du.Age.astype("int")

In [135]:
du

   Age Department   Salary  updated_salary  updated_salary_2
0   25         HR  50000.0         56000.0           90900.0
1   30         IT  60000.0         66000.0          100900.0
2   35    Finance  70000.0         76000.0          110900.0
5   25         HR  50000.0         56000.0           90900.0

In [140]:
du["Age"]>25

0    False
1     True
2     True
5    False
Name: Age, dtype: bool

In [141]:
du[du["Age"]>25]

   Age Department   Salary  updated_salary  updated_salary_2
1   30         IT  60000.0         66000.0          100900.0
2   35    Finance  70000.0         76000.0          110900.0

In [144]:
du=pd.read_csv(r"C:\Users\ruthu\Downloads\test2.csv")
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [145]:
du.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [146]:
du["Age"].mean()

np.float64(28.8)

In [147]:
du["Age"]=du["Age"].fillna(value=du["Age"].mean())

In [148]:
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [149]:
du["Salary"].mean()

np.float64(58400.0)

In [150]:
du["Salary"]=du["Salary"].fillna(value=du["Salary"].mean())
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR  58400.0
5           5    Alice  25.0         HR  50000.0

In [152]:
du["Department"].value_counts()

Department
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [153]:
du["Salary"].value_counts()

Salary
50000.0    2
60000.0    1
70000.0    1
62000.0    1
58400.0    1
Name: count, dtype: int64

In [155]:
du=pd.read_csv(r"C:\Users\ruthu\Downloads\test2.csv")
du

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [161]:
du["Age"]=du["Age"].fillna(method="ffill")  #forward fill
du["Salary"]=du["Salary"].fillna(method="bfill") #backward fill
du

C:\Users\ruthu\AppData\Local\Temp\ipykernel_3848\3692182043.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  du["Age"]=du["Age"].fillna(method="ffill")  #forward fill
C:\Users\ruthu\AppData\Local\Temp\ipykernel_3848\3692182043.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  du["Salary"]=du["Salary"].fillna(method="bfill") #backward fill

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  35.0         IT  62000.0
4           4      Eve  29.0         HR  50000.0
5           5    Alice  25.0         HR  50000.0

In [163]:
du.Department.ffill()

0         HR
1         IT
2    Finance
3         IT
4         HR
5         HR
Name: Department, dtype: object

In [164]:
du.Age.ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [168]:
du["updated_salary"]=du["Salary"].apply(lambda x:x+40900)
du

,Unnamed: 0,Name,Age,Department,Salary,updated_salary_2,updated_salary
0,0,Alice,25.0,HR,50000.0,90900.0,90900.0
1,1,Bob,30.0,IT,60000.0,100900.0,100900.0
2,2,Charlie,35.0,Finance,70000.0,110900.0,110900.0
3,3,David,35.0,IT,62000.0,102900.0,102900.0
4,4,Eve,29.0,HR,50000.0,90900.0,90900.0
5,5,Alice,25.0,HR,50000.0,90900.0,90900.0

In [174]:
du["Level"]= du.apply(lambda s:"High" if s ["updated_salary"] > 100000 else "Low", axis=1)

In [175]:
du

,Unnamed: 0,Name,Age,Department,Salary,updated_salary_2,updated_salary,Level
0,0,Alice,25.0,HR,50000.0,90900.0,90900.0,Low
1,1,Bob,30.0,IT,60000.0,100900.0,100900.0,High
2,2,Charlie,35.0,Finance,70000.0,110900.0,110900.0,High
3,3,David,35.0,IT,62000.0,102900.0,102900.0,High
4,4,Eve,29.0,HR,50000.0,90900.0,90900.0,Low
5,5,Alice,25.0,HR,50000.0,90900.0,90900.0,Low

In [177]:
du.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         50000.0
IT         61000.0
Name: Salary, dtype: float64